# CLI apps
brew "eza" # `ls` replacement
brew "git"
brew "curl"
brew "starship"
brew "zellij"

# GUI apps
cask "1password" # Password manager

cask "numi" # Calculator
cask "jordanbaird-ice" # Hides menu bar icons
cask "raycast" # App launcher
cask "obsidian" # Markdown editor
cask "zen-browser" # Browser
cask "zed" # Editor

cask "telegram" # Messenger
cask "zoom" # Video conferencing
cask "spotify" # Music

cask "orbstack"
cask "docker"

cask "jetbrains-toolbox" # IDE
cask "karabiner-elements" # Keyboard shortcuts
cask "dash" # Documentation reader

