# COLORS SECTION STARTS
[colors]
[colors.primary]
background = "#272b30"

[colors.normal]
black = "#272b30"
red = "#cc6666"
green = "#bdb968"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b08cba"
cyan = "#7fb2c8"
white = "#afb4c3"
# COLORS SECTION ENDS
